inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 160

Style/MixinUsage:
  Enabled: false

#クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

#モジュール名：クラス名の定義を無視
Style/ClassAndModuleChildren:
  Enabled: false

#日本語でのコメントを許可
AsciiComments:
  Enabled: false

#メソッド記述複数行にする
Style/EmptyMethod:
  EnforcedStyle: expanded

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 13
